config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  resources :routes
  resources :railway_stations
  resources :trains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  paginates_per 5
  validates :title, presence: true

  has_many :railway_stations_routes, dependent: :destroy
  has_many :routes, through: :railway_stations_routes
  has_many :trains
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :route
  belongs_to :railway_station
end

app/models/route.rb
class Route < ApplicationRecord
  paginates_per 5
  validates :title, presence: true

  has_many :railway_stations_routes, dependent: :destroy
  has_many :railway_stations, through: :railway_stations_routes

  has_many :trains
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :end_station, :start_station, presence: true

  belongs_to :train
  belongs_to :user
end

app/models/train.rb
class Train < ApplicationRecord
  paginates_per 5
  validates :number, presence: true

  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation',
                               foreign_key: :railway_station_id, optional: true
  has_many :tickets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tickets
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json, :js

  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, except: %i[index new create]

  def index
    @railway_stations = RailwayStation.order(id: :asc).page params[:page]
    respond_with @railway_stations
  end

  def show; end

  def new
    respond_with @railway_station = RailwayStation.new
  end

  def edit; end

  def create
    respond_with @railway_station = RailwayStation.create(railway_station_params)
  end

  def update
    @railway_station.update(railway_station_params)
    respond_with @railway_station
  end

  def destroy
    respond_with @railway_station.destroy
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, except: %i[index new create]

  def index
    @routes = Route.order(id: :asc).page params[:page]
    respond_with @routes
  end

  def show; end

  def new
    respond_with @route = Route.new
  end

  def edit; end

  def create
    respond_with @route = Route.create(route_params)
  end

  def update
    @route.update(route_params)
    respond_with @route
  end

  def destroy
    respond_with @route.destroy
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, except: %i[new create index]

  def index
    @trains = Train.order(id: :asc).page params[:page]
    respond_with @trains
  end

  def show; end

  def new
    respond_with @train = Train.new
  end

  def edit; end

  def create
    respond_with @train = Train.create(train_params)
  end

  def update
    @train.update(train_params)
    respond_with @train
  end

  def destroy
    respond_with @train.destroy
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, 'error')} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/common/_errors.html.slim
- if resource.errors.any?
  #error_explanation
    - resource.errors.messages.each do |attr, msg|
      p.alert.alert-danger #{attr}  #{msg[0]}

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-sm.navbar-light.bg-light
  = link_to 'Tutu', root_path, class: 'navbar-brand'
  #nav-content.collapse.navbar-collapse.justify-content-end
    ul.navbar-nav
      - if user_signed_in?
        li = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-primary'
      - else
        li = link_to 'Sign in', new_user_session_path, class: 'btn btn-primary'

app/views/layouts/_list_group.html.slim
.list-group
  = link_to 'Routes', routes_path,
          class: "list-group-item list-group-item-action #{active_class(routes_path)}"
  = link_to 'Railway Stations', railway_stations_path,
          class: "list-group-item list-group-item-action #{active_class(railway_stations_path)}"
  = link_to 'Trains', trains_path,
          class: "list-group-item list-group-item-action #{active_class(trains_path)}"

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  div class="alert alert-#{key}"
    a.close data-dismiss="alert" href="#" ×
    span = value

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=('text/html; charset=UTF-8') http-equiv="Content-Type" /
    title Tutu
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container.margin-top-50
      = render 'layouts/messages'
      .row.margin-top-30
        .col-9
          = yield
        .col-3
          - if user_signed_in?
            = render 'layouts/list_group'

app/views/railway_stations/_form.html.slim
= form_for railway_station do |f|
  .form-row
    .form-group.col-6
      = f.label :title
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.submit "#{railway_station.new_record? ? 'Create' : 'Edit'}", class: 'btn btn-primary'

app/views/railway_stations/destroy.js.erb
$('a.btn-danger[data-railway-station-id="<%= @railway_station.id %>"]').closest('tr').remove();

app/views/railway_stations/edit.html.slim
h2 Fill in all the necessary information to update the railway station
= render 'common/errors', resource: @railway_station
= render 'railway_stations/form', railway_station: @railway_station

app/views/railway_stations/index.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Id
      th Title
      th Show
      th Edit
      th Delete
  tbody
    - @railway_stations.each do |station|
      tr
        td  = station.id
        td  = station.title
        td  = link_to 'See more ...', station, class: 'btn btn-info'
        td  = link_to 'Update', edit_railway_station_path(station), class: 'btn btn-success'
        td  = link_to 'Destroy', station, class: 'btn btn-danger',
                remote: true, method: :delete, data: { railway_station_id: station.id }

= link_to 'Add Railway Station', new_railway_station_path, class: 'btn btn-primary float-right'
= paginate @railway_stations, theme: 'twitter-bootstrap-4'

app/views/railway_stations/new.html.slim
h2 Fill in all the necessary information to create the railway station
= render 'common/errors', resource: @railway_station
= render 'railway_stations/form', railway_station: @railway_station

app/views/railway_stations/show.html.slim
h2 = "Information about railway station '#{@railway_station.title}'"
br
h4 Title:
p = @railway_station.title

app/views/routes/_form.html.slim
= form_for route do |f|
  .form-row
    .form-group.col-6
      = f.label :title
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.submit "#{route.new_record? ? 'Create' : 'Edit'}", class: 'btn btn-primary'

app/views/routes/destroy.js.erb
$('a.btn-danger[data-route-id="<%= @route.id %>"]').closest('tr').remove();

app/views/routes/edit.html.slim
h2 Fill in all the necessary information to update the route
= render 'common/errors', resource: @route
= render 'routes/form', route: @route

app/views/routes/index.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Id
      th Title
      th Show
      th Edit
      th Delete
  tbody
    - @routes.each do |route|
      tr
        td  = route.id
        td  = route.title
        td  = link_to 'See more ...', route, class: 'btn btn-info'
        td  = link_to 'Update', edit_route_path(route), class: 'btn btn-success'
        td  = link_to 'Destroy', route, class: 'btn btn-danger',
                                 remote: true, method: :delete, data: { route_id: route.id }

= link_to 'Add Route', new_route_path, class: 'btn btn-primary float-right'
= paginate @routes, theme: 'twitter-bootstrap-4'

app/views/routes/new.html.slim
h2 Fill in all the necessary information to create the route
= render 'common/errors', resource: @route
= render 'routes/form', route: @route

app/views/routes/show.html.slim
h2 = "Information about route '#{@route.title}'"
br
h4 Title:
p = @route.title

app/views/trains/_form.html.slim
= form_for train do |f|
  .form-row
    .form-group.col-6
      = f.label :number
      = f.text_field :number, class: 'form-control'
  .form-group
    = f.submit "#{train.new_record? ? 'Create' : 'Edit'}", class: 'btn btn-primary'

app/views/trains/destroy.js.erb
$('a.btn-danger[data-train-id="<%= @train.id %>"]').closest('tr').remove();

app/views/trains/edit.html.slim
h2 Fill in all the necessary information to update the train
= render 'common/errors', resource: @train
= render 'trains/form', train: @train

app/views/trains/index.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Id
      th Number
      th Show
      th Edit
      th Delete
  tbody
    - @trains.each do |train|
      tr
        td  = train.id
        td  = train.number
        td  = link_to 'See more ...', train, class: 'btn btn-info'
        td  = link_to 'Update', edit_train_path(train), class: 'btn btn-success'
        td  = link_to 'Destroy', train, class: 'btn btn-danger',
                remote: true, method: :delete, data: { train_id: train.id }

= link_to 'Add Train', new_train_path, class: 'btn btn-primary float-right'
= paginate @trains, theme: 'twitter-bootstrap-4'

app/views/trains/new.html.slim
h2 Fill in all the necessary information to create the train
= render 'common/errors', resource: @train
= render 'trains/form', train: @train

app/views/trains/show.html.slim
h2 = "Information about train '#{@train.number}'"
br
h4 Number:
p = @train.number

app/views/welcome/index.html.slim
h1 Welcome to App !